<?php

namespace Database\Seeders;

use App\Models\SystemCountry;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SystemCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [
                'name' => "Afghanistan",
                'short_name' => "Afghanistan",
                'iso2' => "AF",
                'iso3' => "AFG",
                'numeric_code' => "4",
                'calling_code' => "+93",
                'capital' => "Kabul",
                'currency' => "AFN",
                'currency_symbol' => "؋"
            ],
            [
                'name' => "Aland Islands",
                'short_name' => "Aland Islands",
                'iso2' => "AX",
                'iso3' => "ALA",
                'numeric_code' => "248",
                'calling_code' => "+358",
                'capital' => "Mariehamn",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Albania",
                'short_name' => "Albania",
                'iso2' => "AL",
                'iso3' => "ALB",
                'numeric_code' => "8",
                'calling_code' => "+355",
                'capital' => "Tirana",
                'currency' => "ALL",
                'currency_symbol' => "Lek"
            ],
            [
                'name' => "Algeria",
                'short_name' => "Algeria",
                'iso2' => "DZ",
                'iso3' => "DZA",
                'numeric_code' => "12",
                'calling_code' => "+213",
                'capital' => "Algiers",
                'currency' => "DZD",
                'currency_symbol' => "دج"
            ],
            [
                'name' => "American Samoa",
                'short_name' => "American Samoa",
                'iso2' => "AS",
                'iso3' => "ASM",
                'numeric_code' => "16",
                'calling_code' => "+1",
                'capital' => "Pago Pago",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Andorra",
                'short_name' => "Andorra",
                'iso2' => "AD",
                'iso3' => "AND",
                'numeric_code' => "20",
                'calling_code' => "+376",
                'capital' => "Andorra la Vella",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Angola",
                'short_name' => "Angola",
                'iso2' => "AO",
                'iso3' => "AGO",
                'numeric_code' => "24",
                'calling_code' => "+244",
                'capital' => "Luanda",
                'currency' => "AOA",
                'currency_symbol' => "Kz"
            ],
            [
                'name' => "Anguilla",
                'short_name' => "Anguilla",
                'iso2' => "AI",
                'iso3' => "AIA",
                'numeric_code' => "660",
                'calling_code' => "+1",
                'capital' => "The Valley",
                'currency' => "XCD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Antarctica",
                'short_name' => "Antarctica",
                'iso2' => "AQ",
                'iso3' => "ATA",
                'numeric_code' => "10",
                'calling_code' => "+672",
                'capital' => "nan",
                'currency' => "AAD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Antigua and Barbuda",
                'short_name' => "Antigua and Barbuda",
                'iso2' => "AG",
                'iso3' => "ATG",
                'numeric_code' => "28",
                'calling_code' => "+1",
                'capital' => "St. John's",
                'currency' => "XCD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Argentina",
                'short_name' => "Argentina",
                'iso2' => "AR",
                'iso3' => "ARG",
                'numeric_code' => "32",
                'calling_code' => "+54",
                'capital' => "Buenos Aires",
                'currency' => "ARS",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Armenia",
                'short_name' => "Armenia",
                'iso2' => "AM",
                'iso3' => "ARM",
                'numeric_code' => "51",
                'calling_code' => "+374",
                'capital' => "Yerevan",
                'currency' => "AMD",
                'currency_symbol' => "֏"
            ],
            [
                'name' => "Aruba",
                'short_name' => "Aruba",
                'iso2' => "AW",
                'iso3' => "ABW",
                'numeric_code' => "533",
                'calling_code' => "+297",
                'capital' => "Oranjestad",
                'currency' => "AWG",
                'currency_symbol' => "ƒ"
            ],
            [
                'name' => "Australia",
                'short_name' => "Australia",
                'iso2' => "AU",
                'iso3' => "AUS",
                'numeric_code' => "36",
                'calling_code' => "+61",
                'capital' => "Canberra",
                'currency' => "AUD",
                'currency_symbol' => "$",
                'active' => '1'
            ],
            [
                'name' => "Austria",
                'short_name' => "Austria",
                'iso2' => "AT",
                'iso3' => "AUT",
                'numeric_code' => "40",
                'calling_code' => "+43",
                'capital' => "Vienna",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Azerbaijan",
                'short_name' => "Azerbaijan",
                'iso2' => "AZ",
                'iso3' => "AZE",
                'numeric_code' => "31",
                'calling_code' => "+994",
                'capital' => "Baku",
                'currency' => "AZN",
                'currency_symbol' => "m"
            ],
            [
                'name' => "Bahrain",
                'short_name' => "Bahrain",
                'iso2' => "BH",
                'iso3' => "BHR",
                'numeric_code' => "48",
                'calling_code' => "+973",
                'capital' => "Manama",
                'currency' => "BHD",
                'currency_symbol' => ".د.ب"
            ],
            [
                'name' => "Bangladesh",
                'short_name' => "Bangladesh",
                'iso2' => "BD",
                'iso3' => "BGD",
                'numeric_code' => "50",
                'calling_code' => "+880",
                'capital' => "Dhaka",
                'currency' => "BDT",
                'currency_symbol' => "৳"
            ],
            [
                'name' => "Barbados",
                'short_name' => "Barbados",
                'iso2' => "BB",
                'iso3' => "BRB",
                'numeric_code' => "52",
                'calling_code' => "+1",
                'capital' => "Bridgetown",
                'currency' => "BBD",
                'currency_symbol' => "Bds$"
            ],
            [
                'name' => "Belarus",
                'short_name' => "Belarus",
                'iso2' => "BY",
                'iso3' => "BLR",
                'numeric_code' => "112",
                'calling_code' => "+375",
                'capital' => "Minsk",
                'currency' => "BYN",
                'currency_symbol' => "Br"
            ],
            [
                'name' => "Belgium",
                'short_name' => "Belgium",
                'iso2' => "BE",
                'iso3' => "BEL",
                'numeric_code' => "56",
                'calling_code' => "+32",
                'capital' => "Brussels",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Belize",
                'short_name' => "Belize",
                'iso2' => "BZ",
                'iso3' => "BLZ",
                'numeric_code' => "84",
                'calling_code' => "+501",
                'capital' => "Belmopan",
                'currency' => "BZD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Benin",
                'short_name' => "Benin",
                'iso2' => "BJ",
                'iso3' => "BEN",
                'numeric_code' => "204",
                'calling_code' => "+229",
                'capital' => "Porto-Novo",
                'currency' => "XOF",
                'currency_symbol' => "CFA"
            ],
            [
                'name' => "Bermuda",
                'short_name' => "Bermuda",
                'iso2' => "BM",
                'iso3' => "BMU",
                'numeric_code' => "60",
                'calling_code' => "+1",
                'capital' => "Hamilton",
                'currency' => "BMD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Bhutan",
                'short_name' => "Bhutan",
                'iso2' => "BT",
                'iso3' => "BTN",
                'numeric_code' => "64",
                'calling_code' => "+975",
                'capital' => "Thimphu",
                'currency' => "BTN",
                'currency_symbol' => "Nu."
            ],
            [
                'name' => "Bolivia",
                'short_name' => "Bolivia",
                'iso2' => "BO",
                'iso3' => "BOL",
                'numeric_code' => "68",
                'calling_code' => "+591",
                'capital' => "Sucre",
                'currency' => "BOB",
                'currency_symbol' => "Bs."
            ],
            [
                'name' => "Bonaire, Sint Eustatius and Saba",
                'short_name' => "Bonaire, Sint Eustatius and Saba",
                'iso2' => "BQ",
                'iso3' => "BES",
                'numeric_code' => "535",
                'calling_code' => "+599",
                'capital' => "Kralendijk",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Bosnia and Herzegovina",
                'short_name' => "Bosnia and Herzegovina",
                'iso2' => "BA",
                'iso3' => "BIH",
                'numeric_code' => "70",
                'calling_code' => "+387",
                'capital' => "Sarajevo",
                'currency' => "BAM",
                'currency_symbol' => "KM"
            ],
            [
                'name' => "Botswana",
                'short_name' => "Botswana",
                'iso2' => "BW",
                'iso3' => "BWA",
                'numeric_code' => "72",
                'calling_code' => "+267",
                'capital' => "Gaborone",
                'currency' => "BWP",
                'currency_symbol' => "P"
            ],
            [
                'name' => "Bouvet Island",
                'short_name' => "Bouvet Island",
                'iso2' => "BV",
                'iso3' => "BVT",
                'numeric_code' => "74",
                'calling_code' => "+55",
                'capital' => "nan",
                'currency' => "NOK",
                'currency_symbol' => "ko"
            ],
            [
                'name' => "Brazil",
                'short_name' => "Brazil",
                'iso2' => "BR",
                'iso3' => "BRA",
                'numeric_code' => "76",
                'calling_code' => "+55",
                'capital' => "Brasilia",
                'currency' => "BRL",
                'currency_symbol' => "R$",
                'active' => '1'
            ],
            [
                'name' => "British Indian Ocean Territory",
                'short_name' => "British Indian Ocean Territory",
                'iso2' => "IO",
                'iso3' => "IOT",
                'numeric_code' => "86",
                'calling_code' => "+246",
                'capital' => "Diego Garcia",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Brunei",
                'short_name' => "Brunei",
                'iso2' => "BN",
                'iso3' => "BRN",
                'numeric_code' => "96",
                'calling_code' => "+673",
                'capital' => "Bandar Seri Begawan",
                'currency' => "BND",
                'currency_symbol' => "B$"
            ],
            [
                'name' => "Bulgaria",
                'short_name' => "Bulgaria",
                'iso2' => "BG",
                'iso3' => "BGR",
                'numeric_code' => "100",
                'calling_code' => "+359",
                'capital' => "Sofia",
                'currency' => "BGN",
                'currency_symbol' => "Лв."
            ],
            [
                'name' => "Burkina Faso",
                'short_name' => "Burkina Faso",
                'iso2' => "BF",
                'iso3' => "BFA",
                'numeric_code' => "854",
                'calling_code' => "+226",
                'capital' => "Ouagadougou",
                'currency' => "XOF",
                'currency_symbol' => "CFA"
            ],
            [
                'name' => "Burundi",
                'short_name' => "Burundi",
                'iso2' => "BI",
                'iso3' => "BDI",
                'numeric_code' => "108",
                'calling_code' => "+257",
                'capital' => "Bujumbura",
                'currency' => "BIF",
                'currency_symbol' => "FBu"
            ],
            [
                'name' => "Cambodia",
                'short_name' => "Cambodia",
                'iso2' => "KH",
                'iso3' => "KHM",
                'numeric_code' => "116",
                'calling_code' => "+855",
                'capital' => "Phnom Penh",
                'currency' => "KHR",
                'currency_symbol' => "KHR"
            ],
            [
                'name' => "Cameroon",
                'short_name' => "Cameroon",
                'iso2' => "CM",
                'iso3' => "CMR",
                'numeric_code' => "120",
                'calling_code' => "+237",
                'capital' => "Yaounde",
                'currency' => "XAF",
                'currency_symbol' => "FCFA"
            ],
            [
                'name' => "Canada",
                'short_name' => "Canada",
                'iso2' => "CA",
                'iso3' => "CAN",
                'numeric_code' => "124",
                'calling_code' => "+1",
                'capital' => "Ottawa",
                'currency' => "CAD",
                'currency_symbol' => "$",
                'active' => '1'
            ],
            [
                'name' => "Cape Verde",
                'short_name' => "Cape Verde",
                'iso2' => "CV",
                'iso3' => "CPV",
                'numeric_code' => "132",
                'calling_code' => "+238",
                'capital' => "Praia",
                'currency' => "CVE",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Cayman Islands",
                'short_name' => "Cayman Islands",
                'iso2' => "KY",
                'iso3' => "CYM",
                'numeric_code' => "136",
                'calling_code' => "+1",
                'capital' => "George Town",
                'currency' => "KYD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Central African Republic",
                'short_name' => "Central African Republic",
                'iso2' => "CF",
                'iso3' => "CAF",
                'numeric_code' => "140",
                'calling_code' => "+236",
                'capital' => "Bangui",
                'currency' => "XAF",
                'currency_symbol' => "FCFA"
            ],
            [
                'name' => "Chad",
                'short_name' => "Chad",
                'iso2' => "TD",
                'iso3' => "TCD",
                'numeric_code' => "148",
                'calling_code' => "+235",
                'capital' => "N'Djamena",
                'currency' => "XAF",
                'currency_symbol' => "FCFA"
            ],
            [
                'name' => "Chile",
                'short_name' => "Chile",
                'iso2' => "CL",
                'iso3' => "CHL",
                'numeric_code' => "152",
                'calling_code' => "+56",
                'capital' => "Santiago",
                'currency' => "CLP",
                'currency_symbol' => "$"
            ],
            [
                'name' => "China",
                'short_name' => "China",
                'iso2' => "CN",
                'iso3' => "CHN",
                'numeric_code' => "156",
                'calling_code' => "+86",
                'capital' => "Beijing",
                'currency' => "CNY",
                'currency_symbol' => "¥"
            ],
            [
                'name' => "Christmas Island",
                'short_name' => "Christmas Island",
                'iso2' => "CX",
                'iso3' => "CXR",
                'numeric_code' => "162",
                'calling_code' => "+61",
                'capital' => "Flying Fish Cove",
                'currency' => "AUD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Cocos (Keeling) Islands",
                'short_name' => "Cocos (Keeling) Islands",
                'iso2' => "CC",
                'iso3' => "CCK",
                'numeric_code' => "166",
                'calling_code' => "+61",
                'capital' => "West Island",
                'currency' => "AUD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Colombia",
                'short_name' => "Colombia",
                'iso2' => "CO",
                'iso3' => "COL",
                'numeric_code' => "170",
                'calling_code' => "+57",
                'capital' => "Bogotá",
                'currency' => "COP",
                'currency_symbol' => "$",
                'active' => '1'
            ],
            [
                'name' => "Comoros",
                'short_name' => "Comoros",
                'iso2' => "KM",
                'iso3' => "COM",
                'numeric_code' => "174",
                'calling_code' => "+269",
                'capital' => "Moroni",
                'currency' => "KMF",
                'currency_symbol' => "CF"
            ],
            [
                'name' => "Congo",
                'short_name' => "Congo",
                'iso2' => "CG",
                'iso3' => "COG",
                'numeric_code' => "178",
                'calling_code' => "+242",
                'capital' => "Brazzaville",
                'currency' => "XAF",
                'currency_symbol' => "CDF"
            ],
            [
                'name' => "Cook Islands",
                'short_name' => "Cook Islands",
                'iso2' => "CK",
                'iso3' => "COK",
                'numeric_code' => "184",
                'calling_code' => "+682",
                'capital' => "Avarua",
                'currency' => "NZD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Costa Rica",
                'short_name' => "Costa Rica",
                'iso2' => "CR",
                'iso3' => "CRI",
                'numeric_code' => "188",
                'calling_code' => "+506",
                'capital' => "San Jose",
                'currency' => "CRC",
                'currency_symbol' => "₡"
            ],
            [
                'name' => "Cote D'Ivoire (Ivory Coast)",
                'short_name' => "Cote D'Ivoire (Ivory Coast)",
                'iso2' => "CI",
                'iso3' => "CIV",
                'numeric_code' => "384",
                'calling_code' => "+225",
                'capital' => "Yamoussoukro",
                'currency' => "XOF",
                'currency_symbol' => "CFA"
            ],
            [
                'name' => "Croatia",
                'short_name' => "Croatia",
                'iso2' => "HR",
                'iso3' => "HRV",
                'numeric_code' => "191",
                'calling_code' => "+385",
                'capital' => "Zagreb",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Cuba",
                'short_name' => "Cuba",
                'iso2' => "CU",
                'iso3' => "CUB",
                'numeric_code' => "192",
                'calling_code' => "+53",
                'capital' => "Havana",
                'currency' => "CUP",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Curaçao",
                'short_name' => "Curaçao",
                'iso2' => "CW",
                'iso3' => "CUW",
                'numeric_code' => "531",
                'calling_code' => "+599",
                'capital' => "Willemstad",
                'currency' => "ANG",
                'currency_symbol' => "ƒ"
            ],
            [
                'name' => "Cyprus",
                'short_name' => "Cyprus",
                'iso2' => "CY",
                'iso3' => "CYP",
                'numeric_code' => "196",
                'calling_code' => "+357",
                'capital' => "Nicosia",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Czech Republic",
                'short_name' => "Czech Republic",
                'iso2' => "CZ",
                'iso3' => "CZE",
                'numeric_code' => "203",
                'calling_code' => "+420",
                'capital' => "Prague",
                'currency' => "CZK",
                'currency_symbol' => "Kč"
            ],
            [
                'name' => "Democratic Republic of the Congo",
                'short_name' => "Democratic Republic of the Congo",
                'iso2' => "CD",
                'iso3' => "COD",
                'numeric_code' => "180",
                'calling_code' => "+243",
                'capital' => "Kinshasa",
                'currency' => "CDF",
                'currency_symbol' => "FC"
            ],
            [
                'name' => "Denmark",
                'short_name' => "Denmark",
                'iso2' => "DK",
                'iso3' => "DNK",
                'numeric_code' => "208",
                'calling_code' => "+45",
                'capital' => "Copenhagen",
                'currency' => "DKK",
                'currency_symbol' => "Kr."
            ],
            [
                'name' => "Djibouti",
                'short_name' => "Djibouti",
                'iso2' => "DJ",
                'iso3' => "DJI",
                'numeric_code' => "262",
                'calling_code' => "+253",
                'capital' => "Djibouti",
                'currency' => "DJF",
                'currency_symbol' => "Fdj"
            ],
            [
                'name' => "Dominica",
                'short_name' => "Dominica",
                'iso2' => "DM",
                'iso3' => "DMA",
                'numeric_code' => "212",
                'calling_code' => "+1",
                'capital' => "Roseau",
                'currency' => "XCD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Dominican Republic",
                'short_name' => "Dominican Republic",
                'iso2' => "DO",
                'iso3' => "DOM",
                'numeric_code' => "214",
                'calling_code' => "+1",
                'capital' => "Santo Domingo",
                'currency' => "DOP",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Ecuador",
                'short_name' => "Ecuador",
                'iso2' => "EC",
                'iso3' => "ECU",
                'numeric_code' => "218",
                'calling_code' => "+593",
                'capital' => "Quito",
                'currency' => "USD",
                'currency_symbol' => "$",
                'active' => '1'
            ],
            [
                'name' => "Egypt",
                'short_name' => "Egypt",
                'iso2' => "EG",
                'iso3' => "EGY",
                'numeric_code' => "818",
                'calling_code' => "+20",
                'capital' => "Cairo",
                'currency' => "EGP",
                'currency_symbol' => "ج.م"
            ],
            [
                'name' => "El Salvador",
                'short_name' => "El Salvador",
                'iso2' => "SV",
                'iso3' => "SLV",
                'numeric_code' => "222",
                'calling_code' => "+503",
                'capital' => "San Salvador",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Equatorial Guinea",
                'short_name' => "Equatorial Guinea",
                'iso2' => "GQ",
                'iso3' => "GNQ",
                'numeric_code' => "226",
                'calling_code' => "+240",
                'capital' => "Malabo",
                'currency' => "XAF",
                'currency_symbol' => "FCFA"
            ],
            [
                'name' => "Eritrea",
                'short_name' => "Eritrea",
                'iso2' => "ER",
                'iso3' => "ERI",
                'numeric_code' => "232",
                'calling_code' => "+291",
                'capital' => "Asmara",
                'currency' => "ERN",
                'currency_symbol' => "Nfk"
            ],
            [
                'name' => "Estonia",
                'short_name' => "Estonia",
                'iso2' => "EE",
                'iso3' => "EST",
                'numeric_code' => "233",
                'calling_code' => "+372",
                'capital' => "Tallinn",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Eswatini",
                'short_name' => "Eswatini",
                'iso2' => "SZ",
                'iso3' => "SWZ",
                'numeric_code' => "748",
                'calling_code' => "+268",
                'capital' => "Mbabane",
                'currency' => "SZL",
                'currency_symbol' => "E"
            ],
            [
                'name' => "Ethiopia",
                'short_name' => "Ethiopia",
                'iso2' => "ET",
                'iso3' => "ETH",
                'numeric_code' => "231",
                'calling_code' => "+251",
                'capital' => "Addis Ababa",
                'currency' => "ETB",
                'currency_symbol' => "Nkf"
            ],
            [
                'name' => "Falkland Islands",
                'short_name' => "Falkland Islands",
                'iso2' => "FK",
                'iso3' => "FLK",
                'numeric_code' => "238",
                'calling_code' => "+500",
                'capital' => "Stanley",
                'currency' => "FKP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "Faroe Islands",
                'short_name' => "Faroe Islands",
                'iso2' => "FO",
                'iso3' => "FRO",
                'numeric_code' => "234",
                'calling_code' => "+298",
                'capital' => "Torshavn",
                'currency' => "DKK",
                'currency_symbol' => "Kr."
            ],
            [
                'name' => "Fiji Islands",
                'short_name' => "Fiji Islands",
                'iso2' => "FJ",
                'iso3' => "FJI",
                'numeric_code' => "242",
                'calling_code' => "+679",
                'capital' => "Suva",
                'currency' => "FJD",
                'currency_symbol' => "FJ$"
            ],
            [
                'name' => "Finland",
                'short_name' => "Finland",
                'iso2' => "FI",
                'iso3' => "FIN",
                'numeric_code' => "246",
                'calling_code' => "+358",
                'capital' => "Helsinki",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "France",
                'short_name' => "France",
                'iso2' => "FR",
                'iso3' => "FRA",
                'numeric_code' => "250",
                'calling_code' => "+33",
                'capital' => "Paris",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "French Guiana",
                'short_name' => "French Guiana",
                'iso2' => "GF",
                'iso3' => "GUF",
                'numeric_code' => "254",
                'calling_code' => "+594",
                'capital' => "Cayenne",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "French Polynesia",
                'short_name' => "French Polynesia",
                'iso2' => "PF",
                'iso3' => "PYF",
                'numeric_code' => "258",
                'calling_code' => "+689",
                'capital' => "Papeete",
                'currency' => "XPF",
                'currency_symbol' => "₣"
            ],
            [
                'name' => "French Southern Territories",
                'short_name' => "French Southern Territories",
                'iso2' => "TF",
                'iso3' => "ATF",
                'numeric_code' => "260",
                'calling_code' => "+262",
                'capital' => "Port-aux-Francais",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Gabon",
                'short_name' => "Gabon",
                'iso2' => "GA",
                'iso3' => "GAB",
                'numeric_code' => "266",
                'calling_code' => "+241",
                'capital' => "Libreville",
                'currency' => "XAF",
                'currency_symbol' => "FCFA"
            ],
            [
                'name' => "Georgia",
                'short_name' => "Georgia",
                'iso2' => "GE",
                'iso3' => "GEO",
                'numeric_code' => "268",
                'calling_code' => "+995",
                'capital' => "Tbilisi",
                'currency' => "GEL",
                'currency_symbol' => "ლ"
            ],
            [
                'name' => "Germany",
                'short_name' => "Germany",
                'iso2' => "DE",
                'iso3' => "DEU",
                'numeric_code' => "276",
                'calling_code' => "+49",
                'capital' => "Berlin",
                'currency' => "EUR",
                'currency_symbol' => "€",
                'active' => '1'
            ],
            [
                'name' => "Ghana",
                'short_name' => "Ghana",
                'iso2' => "GH",
                'iso3' => "GHA",
                'numeric_code' => "288",
                'calling_code' => "+233",
                'capital' => "Accra",
                'currency' => "GHS",
                'currency_symbol' => "GH₵"
            ],
            [
                'name' => "Gibraltar",
                'short_name' => "Gibraltar",
                'iso2' => "GI",
                'iso3' => "GIB",
                'numeric_code' => "292",
                'calling_code' => "+350",
                'capital' => "Gibraltar",
                'currency' => "GIP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "Greece",
                'short_name' => "Greece",
                'iso2' => "GR",
                'iso3' => "GRC",
                'numeric_code' => "300",
                'calling_code' => "+30",
                'capital' => "Athens",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Greenland",
                'short_name' => "Greenland",
                'iso2' => "GL",
                'iso3' => "GRL",
                'numeric_code' => "304",
                'calling_code' => "+299",
                'capital' => "Nuuk",
                'currency' => "DKK",
                'currency_symbol' => "Kr."
            ],
            [
                'name' => "Grenada",
                'short_name' => "Grenada",
                'iso2' => "GD",
                'iso3' => "GRD",
                'numeric_code' => "308",
                'calling_code' => "+1",
                'capital' => "St. George's",
                'currency' => "XCD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Guadeloupe",
                'short_name' => "Guadeloupe",
                'iso2' => "GP",
                'iso3' => "GLP",
                'numeric_code' => "312",
                'calling_code' => "+590",
                'capital' => "Basse-Terre",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Guam",
                'short_name' => "Guam",
                'iso2' => "GU",
                'iso3' => "GUM",
                'numeric_code' => "316",
                'calling_code' => "+1",
                'capital' => "Hagatna",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Guatemala",
                'short_name' => "Guatemala",
                'iso2' => "GT",
                'iso3' => "GTM",
                'numeric_code' => "320",
                'calling_code' => "+502",
                'capital' => "Guatemala City",
                'currency' => "GTQ",
                'currency_symbol' => "Q"
            ],
            [
                'name' => "Guernsey and Alderney",
                'short_name' => "Guernsey and Alderney",
                'iso2' => "GG",
                'iso3' => "GGY",
                'numeric_code' => "831",
                'calling_code' => "+44",
                'capital' => "St Peter Port",
                'currency' => "GBP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "Guinea",
                'short_name' => "Guinea",
                'iso2' => "GN",
                'iso3' => "GIN",
                'numeric_code' => "324",
                'calling_code' => "+224",
                'capital' => "Conakry",
                'currency' => "GNF",
                'currency_symbol' => "FG"
            ],
            [
                'name' => "Guinea-Bissau",
                'short_name' => "Guinea-Bissau",
                'iso2' => "GW",
                'iso3' => "GNB",
                'numeric_code' => "624",
                'calling_code' => "+245",
                'capital' => "Bissau",
                'currency' => "XOF",
                'currency_symbol' => "CFA"
            ],
            [
                'name' => "Guyana",
                'short_name' => "Guyana",
                'iso2' => "GY",
                'iso3' => "GUY",
                'numeric_code' => "328",
                'calling_code' => "+592",
                'capital' => "Georgetown",
                'currency' => "GYD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Haiti",
                'short_name' => "Haiti",
                'iso2' => "HT",
                'iso3' => "HTI",
                'numeric_code' => "332",
                'calling_code' => "+509",
                'capital' => "Port-au-Prince",
                'currency' => "HTG",
                'currency_symbol' => "G"
            ],
            [
                'name' => "Heard Island and McDonald Islands",
                'short_name' => "Heard Island and McDonald Islands",
                'iso2' => "HM",
                'iso3' => "HMD",
                'numeric_code' => "334",
                'calling_code' => "+672",
                'capital' => "nan",
                'currency' => "AUD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Honduras",
                'short_name' => "Honduras",
                'iso2' => "HN",
                'iso3' => "HND",
                'numeric_code' => "340",
                'calling_code' => "+504",
                'capital' => "Tegucigalpa",
                'currency' => "HNL",
                'currency_symbol' => "L"
            ],
            [
                'name' => "Hong Kong S.A.R.",
                'short_name' => "Hong Kong S.A.R.",
                'iso2' => "HK",
                'iso3' => "HKG",
                'numeric_code' => "344",
                'calling_code' => "+852",
                'capital' => "Hong Kong",
                'currency' => "HKD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Hungary",
                'short_name' => "Hungary",
                'iso2' => "HU",
                'iso3' => "HUN",
                'numeric_code' => "348",
                'calling_code' => "+36",
                'capital' => "Budapest",
                'currency' => "HUF",
                'currency_symbol' => "Ft"
            ],
            [
                'name' => "Iceland",
                'short_name' => "Iceland",
                'iso2' => "IS",
                'iso3' => "ISL",
                'numeric_code' => "352",
                'calling_code' => "+354",
                'capital' => "Reykjavik",
                'currency' => "ISK",
                'currency_symbol' => "ko"
            ],
            [
                'name' => "India",
                'short_name' => "India",
                'iso2' => "IN",
                'iso3' => "IND",
                'numeric_code' => "356",
                'calling_code' => "+91",
                'capital' => "New Delhi",
                'currency' => "INR",
                'currency_symbol' => "₹"
            ],
            [
                'name' => "Indonesia",
                'short_name' => "Indonesia",
                'iso2' => "ID",
                'iso3' => "IDN",
                'numeric_code' => "360",
                'calling_code' => "+62",
                'capital' => "Jakarta",
                'currency' => "IDR",
                'currency_symbol' => "Rp"
            ],
            [
                'name' => "Iran",
                'short_name' => "Iran",
                'iso2' => "IR",
                'iso3' => "IRN",
                'numeric_code' => "364",
                'calling_code' => "+98",
                'capital' => "Tehran",
                'currency' => "IRR",
                'currency_symbol' => "﷼"
            ],
            [
                'name' => "Iraq",
                'short_name' => "Iraq",
                'iso2' => "IQ",
                'iso3' => "IRQ",
                'numeric_code' => "368",
                'calling_code' => "+964",
                'capital' => "Baghdad",
                'currency' => "IQD",
                'currency_symbol' => "د.ع"
            ],
            [
                'name' => "Ireland",
                'short_name' => "Ireland",
                'iso2' => "IE",
                'iso3' => "IRL",
                'numeric_code' => "372",
                'calling_code' => "+353",
                'capital' => "Dublin",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Israel",
                'short_name' => "Israel",
                'iso2' => "IL",
                'iso3' => "ISR",
                'numeric_code' => "376",
                'calling_code' => "+972",
                'capital' => "Jerusalem",
                'currency' => "ILS",
                'currency_symbol' => "₪"
            ],
            [
                'name' => "Italy",
                'short_name' => "Italy",
                'iso2' => "IT",
                'iso3' => "ITA",
                'numeric_code' => "380",
                'calling_code' => "+39",
                'capital' => "Rome",
                'currency' => "EUR",
                'currency_symbol' => "€",
                'active' => '1'
            ],
            [
                'name' => "Jamaica",
                'short_name' => "Jamaica",
                'iso2' => "JM",
                'iso3' => "JAM",
                'numeric_code' => "388",
                'calling_code' => "+1",
                'capital' => "Kingston",
                'currency' => "JMD",
                'currency_symbol' => "J$"
            ],
            [
                'name' => "Japan",
                'short_name' => "Japan",
                'iso2' => "JP",
                'iso3' => "JPN",
                'numeric_code' => "392",
                'calling_code' => "+81",
                'capital' => "Tokyo",
                'currency' => "JPY",
                'currency_symbol' => "¥",
                'active' => '1'
            ],
            [
                'name' => "Jersey",
                'short_name' => "Jersey",
                'iso2' => "JE",
                'iso3' => "JEY",
                'numeric_code' => "832",
                'calling_code' => "+44",
                'capital' => "Saint Helier",
                'currency' => "GBP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "Jordan",
                'short_name' => "Jordan",
                'iso2' => "JO",
                'iso3' => "JOR",
                'numeric_code' => "400",
                'calling_code' => "+962",
                'capital' => "Amman",
                'currency' => "JOD",
                'currency_symbol' => "ا.د"
            ],
            [
                'name' => "Kazakhstan",
                'short_name' => "Kazakhstan",
                'iso2' => "KZ",
                'iso3' => "KAZ",
                'numeric_code' => "398",
                'calling_code' => "+7",
                'capital' => "Astana",
                'currency' => "KZT",
                'currency_symbol' => "лв"
            ],
            [
                'name' => "Kenya",
                'short_name' => "Kenya",
                'iso2' => "KE",
                'iso3' => "KEN",
                'numeric_code' => "404",
                'calling_code' => "+254",
                'capital' => "Nairobi",
                'currency' => "KES",
                'currency_symbol' => "KSh"
            ],
            [
                'name' => "Kiribati",
                'short_name' => "Kiribati",
                'iso2' => "KI",
                'iso3' => "KIR",
                'numeric_code' => "296",
                'calling_code' => "+686",
                'capital' => "Tarawa",
                'currency' => "AUD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Kosovo",
                'short_name' => "Kosovo",
                'iso2' => "XK",
                'iso3' => "XKX",
                'numeric_code' => "926",
                'calling_code' => "+383",
                'capital' => "Pristina",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Kuwait",
                'short_name' => "Kuwait",
                'iso2' => "KW",
                'iso3' => "KWT",
                'numeric_code' => "414",
                'calling_code' => "+965",
                'capital' => "Kuwait City",
                'currency' => "KWD",
                'currency_symbol' => "ك.د"
            ],
            [
                'name' => "Kyrgyzstan",
                'short_name' => "Kyrgyzstan",
                'iso2' => "KG",
                'iso3' => "KGZ",
                'numeric_code' => "417",
                'calling_code' => "+996",
                'capital' => "Bishkek",
                'currency' => "KGS",
                'currency_symbol' => "лв"
            ],
            [
                'name' => "Laos",
                'short_name' => "Laos",
                'iso2' => "LA",
                'iso3' => "LAO",
                'numeric_code' => "418",
                'calling_code' => "+856",
                'capital' => "Vientiane",
                'currency' => "LAK",
                'currency_symbol' => "₭"
            ],
            [
                'name' => "Latvia",
                'short_name' => "Latvia",
                'iso2' => "LV",
                'iso3' => "LVA",
                'numeric_code' => "428",
                'calling_code' => "+371",
                'capital' => "Riga",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Lebanon",
                'short_name' => "Lebanon",
                'iso2' => "LB",
                'iso3' => "LBN",
                'numeric_code' => "422",
                'calling_code' => "+961",
                'capital' => "Beirut",
                'currency' => "LBP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "Lesotho",
                'short_name' => "Lesotho",
                'iso2' => "LS",
                'iso3' => "LSO",
                'numeric_code' => "426",
                'calling_code' => "+266",
                'capital' => "Maseru",
                'currency' => "LSL",
                'currency_symbol' => "L"
            ],
            [
                'name' => "Liberia",
                'short_name' => "Liberia",
                'iso2' => "LR",
                'iso3' => "LBR",
                'numeric_code' => "430",
                'calling_code' => "+231",
                'capital' => "Monrovia",
                'currency' => "LRD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Libya",
                'short_name' => "Libya",
                'iso2' => "LY",
                'iso3' => "LBY",
                'numeric_code' => "434",
                'calling_code' => "+218",
                'capital' => "Tripolis",
                'currency' => "LYD",
                'currency_symbol' => "د.ل"
            ],
            [
                'name' => "Liechtenstein",
                'short_name' => "Liechtenstein",
                'iso2' => "LI",
                'iso3' => "LIE",
                'numeric_code' => "438",
                'calling_code' => "+423",
                'capital' => "Vaduz",
                'currency' => "CHF",
                'currency_symbol' => "CHf"
            ],
            [
                'name' => "Lithuania",
                'short_name' => "Lithuania",
                'iso2' => "LT",
                'iso3' => "LTU",
                'numeric_code' => "440",
                'calling_code' => "+370",
                'capital' => "Vilnius",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Luxembourg",
                'short_name' => "Luxembourg",
                'iso2' => "LU",
                'iso3' => "LUX",
                'numeric_code' => "442",
                'calling_code' => "+352",
                'capital' => "Luxembourg",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Macau S.A.R.",
                'short_name' => "Macau S.A.R.",
                'iso2' => "MO",
                'iso3' => "MAC",
                'numeric_code' => "446",
                'calling_code' => "+853",
                'capital' => "Macao",
                'currency' => "MOP",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Madagascar",
                'short_name' => "Madagascar",
                'iso2' => "MG",
                'iso3' => "MDG",
                'numeric_code' => "450",
                'calling_code' => "+261",
                'capital' => "Antananarivo",
                'currency' => "MGA",
                'currency_symbol' => "Ar"
            ],
            [
                'name' => "Malawi",
                'short_name' => "Malawi",
                'iso2' => "MW",
                'iso3' => "MWI",
                'numeric_code' => "454",
                'calling_code' => "+265",
                'capital' => "Lilongwe",
                'currency' => "MWK",
                'currency_symbol' => "MK"
            ],
            [
                'name' => "Malaysia",
                'short_name' => "Malaysia",
                'iso2' => "MY",
                'iso3' => "MYS",
                'numeric_code' => "458",
                'calling_code' => "+60",
                'capital' => "Kuala Lumpur",
                'currency' => "MYR",
                'currency_symbol' => "RM"
            ],
            [
                'name' => "Maldives",
                'short_name' => "Maldives",
                'iso2' => "MV",
                'iso3' => "MDV",
                'numeric_code' => "462",
                'calling_code' => "+960",
                'capital' => "Male",
                'currency' => "MVR",
                'currency_symbol' => "Rf"
            ],
            [
                'name' => "Mali",
                'short_name' => "Mali",
                'iso2' => "ML",
                'iso3' => "MLI",
                'numeric_code' => "466",
                'calling_code' => "+223",
                'capital' => "Bamako",
                'currency' => "XOF",
                'currency_symbol' => "CFA"
            ],
            [
                'name' => "Malta",
                'short_name' => "Malta",
                'iso2' => "MT",
                'iso3' => "MLT",
                'numeric_code' => "470",
                'calling_code' => "+356",
                'capital' => "Valletta",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Man (Isle of)",
                'short_name' => "Man (Isle of)",
                'iso2' => "IM",
                'iso3' => "IMN",
                'numeric_code' => "833",
                'calling_code' => "+44",
                'capital' => "Douglas, Isle of Man",
                'currency' => "GBP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "Marshall Islands",
                'short_name' => "Marshall Islands",
                'iso2' => "MH",
                'iso3' => "MHL",
                'numeric_code' => "584",
                'calling_code' => "+692",
                'capital' => "Majuro",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Martinique",
                'short_name' => "Martinique",
                'iso2' => "MQ",
                'iso3' => "MTQ",
                'numeric_code' => "474",
                'calling_code' => "+596",
                'capital' => "Fort-de-France",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Mauritania",
                'short_name' => "Mauritania",
                'iso2' => "MR",
                'iso3' => "MRT",
                'numeric_code' => "478",
                'calling_code' => "+222",
                'capital' => "Nouakchott",
                'currency' => "MRO",
                'currency_symbol' => "MRU"
            ],
            [
                'name' => "Mauritius",
                'short_name' => "Mauritius",
                'iso2' => "MU",
                'iso3' => "MUS",
                'numeric_code' => "480",
                'calling_code' => "+230",
                'capital' => "Port Louis",
                'currency' => "MUR",
                'currency_symbol' => "₨"
            ],
            [
                'name' => "Mayotte",
                'short_name' => "Mayotte",
                'iso2' => "YT",
                'iso3' => "MYT",
                'numeric_code' => "175",
                'calling_code' => "+262",
                'capital' => "Mamoudzou",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Mexico",
                'short_name' => "Mexico",
                'iso2' => "MX",
                'iso3' => "MEX",
                'numeric_code' => "484",
                'calling_code' => "+52",
                'capital' => "Ciudad de México",
                'currency' => "MXN",
                'currency_symbol' => "$",
                'active' => '1'
            ],
            [
                'name' => "Micronesia",
                'short_name' => "Micronesia",
                'iso2' => "FM",
                'iso3' => "FSM",
                'numeric_code' => "583",
                'calling_code' => "+691",
                'capital' => "Palikir",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Moldova",
                'short_name' => "Moldova",
                'iso2' => "MD",
                'iso3' => "MDA",
                'numeric_code' => "498",
                'calling_code' => "+373",
                'capital' => "Chisinau",
                'currency' => "MDL",
                'currency_symbol' => "L"
            ],
            [
                'name' => "Monaco",
                'short_name' => "Monaco",
                'iso2' => "MC",
                'iso3' => "MCO",
                'numeric_code' => "492",
                'calling_code' => "+377",
                'capital' => "Monaco",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Mongolia",
                'short_name' => "Mongolia",
                'iso2' => "MN",
                'iso3' => "MNG",
                'numeric_code' => "496",
                'calling_code' => "+976",
                'capital' => "Ulan Bator",
                'currency' => "MNT",
                'currency_symbol' => "₮",
                'active' => '1'
            ],
            [
                'name' => "Montenegro",
                'short_name' => "Montenegro",
                'iso2' => "ME",
                'iso3' => "MNE",
                'numeric_code' => "499",
                'calling_code' => "+382",
                'capital' => "Podgorica",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Montserrat",
                'short_name' => "Montserrat",
                'iso2' => "MS",
                'iso3' => "MSR",
                'numeric_code' => "500",
                'calling_code' => "+1",
                'capital' => "Plymouth",
                'currency' => "XCD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Morocco",
                'short_name' => "Morocco",
                'iso2' => "MA",
                'iso3' => "MAR",
                'numeric_code' => "504",
                'calling_code' => "+212",
                'capital' => "Rabat",
                'currency' => "MAD",
                'currency_symbol' => "DH"
            ],
            [
                'name' => "Mozambique",
                'short_name' => "Mozambique",
                'iso2' => "MZ",
                'iso3' => "MOZ",
                'numeric_code' => "508",
                'calling_code' => "+258",
                'capital' => "Maputo",
                'currency' => "MZN",
                'currency_symbol' => "MT"
            ],
            [
                'name' => "Myanmar",
                'short_name' => "Myanmar",
                'iso2' => "MM",
                'iso3' => "MMR",
                'numeric_code' => "104",
                'calling_code' => "+95",
                'capital' => "Nay Pyi Taw",
                'currency' => "MMK",
                'currency_symbol' => "K"
            ],
            [
                'name' => "Namibia",
                'short_name' => "Namibia",
                'iso2' => "NA",
                'iso3' => "NAM",
                'numeric_code' => "516",
                'calling_code' => "+264",
                'capital' => "Windhoek",
                'currency' => "NAD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Nauru",
                'short_name' => "Nauru",
                'iso2' => "NR",
                'iso3' => "NRU",
                'numeric_code' => "520",
                'calling_code' => "+674",
                'capital' => "Yaren",
                'currency' => "AUD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Nepal",
                'short_name' => "Nepal",
                'iso2' => "NP",
                'iso3' => "NPL",
                'numeric_code' => "524",
                'calling_code' => "+977",
                'capital' => "Kathmandu",
                'currency' => "NPR",
                'currency_symbol' => "₨"
            ],
            [
                'name' => "Netherlands",
                'short_name' => "Netherlands",
                'iso2' => "NL",
                'iso3' => "NLD",
                'numeric_code' => "528",
                'calling_code' => "+31",
                'capital' => "Amsterdam",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "New Caledonia",
                'short_name' => "New Caledonia",
                'iso2' => "NC",
                'iso3' => "NCL",
                'numeric_code' => "540",
                'calling_code' => "+687",
                'capital' => "Noumea",
                'currency' => "XPF",
                'currency_symbol' => "₣"
            ],
            [
                'name' => "New Zealand",
                'short_name' => "New Zealand",
                'iso2' => "NZ",
                'iso3' => "NZL",
                'numeric_code' => "554",
                'calling_code' => "+64",
                'capital' => "Wellington",
                'currency' => "NZD",
                'currency_symbol' => "$",
                'active' => '1'
            ],
            [
                'name' => "Nicaragua",
                'short_name' => "Nicaragua",
                'iso2' => "NI",
                'iso3' => "NIC",
                'numeric_code' => "558",
                'calling_code' => "+505",
                'capital' => "Managua",
                'currency' => "NIO",
                'currency_symbol' => "C$"
            ],
            [
                'name' => "Niger",
                'short_name' => "Niger",
                'iso2' => "NE",
                'iso3' => "NER",
                'numeric_code' => "562",
                'calling_code' => "+227",
                'capital' => "Niamey",
                'currency' => "XOF",
                'currency_symbol' => "CFA"
            ],
            [
                'name' => "Nigeria",
                'short_name' => "Nigeria",
                'iso2' => "NG",
                'iso3' => "NGA",
                'numeric_code' => "566",
                'calling_code' => "+234",
                'capital' => "Abuja",
                'currency' => "NGN",
                'currency_symbol' => "₦"
            ],
            [
                'name' => "Niue",
                'short_name' => "Niue",
                'iso2' => "NU",
                'iso3' => "NIU",
                'numeric_code' => "570",
                'calling_code' => "+683",
                'capital' => "Alofi",
                'currency' => "NZD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Norfolk Island",
                'short_name' => "Norfolk Island",
                'iso2' => "NF",
                'iso3' => "NFK",
                'numeric_code' => "574",
                'calling_code' => "+672",
                'capital' => "Kingston",
                'currency' => "AUD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "North Korea",
                'short_name' => "North Korea",
                'iso2' => "KP",
                'iso3' => "PRK",
                'numeric_code' => "408",
                'calling_code' => "+850",
                'capital' => "Pyongyang",
                'currency' => "KPW",
                'currency_symbol' => "₩"
            ],
            [
                'name' => "North Macedonia",
                'short_name' => "North Macedonia",
                'iso2' => "MK",
                'iso3' => "MKD",
                'numeric_code' => "807",
                'calling_code' => "+389",
                'capital' => "Skopje",
                'currency' => "MKD",
                'currency_symbol' => "ден"
            ],
            [
                'name' => "Northern Mariana Islands",
                'short_name' => "Northern Mariana Islands",
                'iso2' => "MP",
                'iso3' => "MNP",
                'numeric_code' => "580",
                'calling_code' => "+1",
                'capital' => "Saipan",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Norway",
                'short_name' => "Norway",
                'iso2' => "NO",
                'iso3' => "NOR",
                'numeric_code' => "578",
                'calling_code' => "+47",
                'capital' => "Oslo",
                'currency' => "NOK",
                'currency_symbol' => "ko",
                'active' => '1'
            ],
            [
                'name' => "Oman",
                'short_name' => "Oman",
                'iso2' => "OM",
                'iso3' => "OMN",
                'numeric_code' => "512",
                'calling_code' => "+968",
                'capital' => "Muscat",
                'currency' => "OMR",
                'currency_symbol' => ".ع.ر"
            ],
            [
                'name' => "Pakistan",
                'short_name' => "Pakistan",
                'iso2' => "PK",
                'iso3' => "PAK",
                'numeric_code' => "586",
                'calling_code' => "+92",
                'capital' => "Islamabad",
                'currency' => "PKR",
                'currency_symbol' => "₨"
            ],
            [
                'name' => "Palau",
                'short_name' => "Palau",
                'iso2' => "PW",
                'iso3' => "PLW",
                'numeric_code' => "585",
                'calling_code' => "+680",
                'capital' => "Melekeok",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Palestinian Territory Occupied",
                'short_name' => "Palestinian Territory Occupied",
                'iso2' => "PS",
                'iso3' => "PSE",
                'numeric_code' => "275",
                'calling_code' => "+970",
                'capital' => "East Jerusalem",
                'currency' => "ILS",
                'currency_symbol' => "₪"
            ],
            [
                'name' => "Panama",
                'short_name' => "Panama",
                'iso2' => "PA",
                'iso3' => "PAN",
                'numeric_code' => "591",
                'calling_code' => "+507",
                'capital' => "Panama City",
                'currency' => "PAB",
                'currency_symbol' => "B/.",
                'active' => '1'
            ],
            [
                'name' => "Papua New Guinea",
                'short_name' => "Papua New Guinea",
                'iso2' => "PG",
                'iso3' => "PNG",
                'numeric_code' => "598",
                'calling_code' => "+675",
                'capital' => "Port Moresby",
                'currency' => "PGK",
                'currency_symbol' => "K"
            ],
            [
                'name' => "Paraguay",
                'short_name' => "Paraguay",
                'iso2' => "PY",
                'iso3' => "PRY",
                'numeric_code' => "600",
                'calling_code' => "+595",
                'capital' => "Asuncion",
                'currency' => "PYG",
                'currency_symbol' => "₲"
            ],
            [
                'name' => "Peru",
                'short_name' => "Peru",
                'iso2' => "PE",
                'iso3' => "PER",
                'numeric_code' => "604",
                'calling_code' => "+51",
                'capital' => "Lima",
                'currency' => "PEN",
                'currency_symbol' => "S/.",
                'active' => '1'
            ],
            [
                'name' => "Philippines",
                'short_name' => "Philippines",
                'iso2' => "PH",
                'iso3' => "PHL",
                'numeric_code' => "608",
                'calling_code' => "+63",
                'capital' => "Manila",
                'currency' => "PHP",
                'currency_symbol' => "₱"
            ],
            [
                'name' => "Pitcairn Island",
                'short_name' => "Pitcairn Island",
                'iso2' => "PN",
                'iso3' => "PCN",
                'numeric_code' => "612",
                'calling_code' => "+870",
                'capital' => "Adamstown",
                'currency' => "NZD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Poland",
                'short_name' => "Poland",
                'iso2' => "PL",
                'iso3' => "POL",
                'numeric_code' => "616",
                'calling_code' => "+48",
                'capital' => "Warsaw",
                'currency' => "PLN",
                'currency_symbol' => "zł"
            ],
            [
                'name' => "Portugal",
                'short_name' => "Portugal",
                'iso2' => "PT",
                'iso3' => "PRT",
                'numeric_code' => "620",
                'calling_code' => "+351",
                'capital' => "Lisbon",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Puerto Rico",
                'short_name' => "Puerto Rico",
                'iso2' => "PR",
                'iso3' => "PRI",
                'numeric_code' => "630",
                'calling_code' => "+1",
                'capital' => "San Juan",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Qatar",
                'short_name' => "Qatar",
                'iso2' => "QA",
                'iso3' => "QAT",
                'numeric_code' => "634",
                'calling_code' => "+974",
                'capital' => "Doha",
                'currency' => "QAR",
                'currency_symbol' => "ق.ر"
            ],
            [
                'name' => "Reunion",
                'short_name' => "Reunion",
                'iso2' => "RE",
                'iso3' => "REU",
                'numeric_code' => "638",
                'calling_code' => "+262",
                'capital' => "Saint-Denis",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Romania",
                'short_name' => "Romania",
                'iso2' => "RO",
                'iso3' => "ROU",
                'numeric_code' => "642",
                'calling_code' => "+40",
                'capital' => "Bucharest",
                'currency' => "RON",
                'currency_symbol' => "lei"
            ],
            [
                'name' => "Russia",
                'short_name' => "Russia",
                'iso2' => "RU",
                'iso3' => "RUS",
                'numeric_code' => "643",
                'calling_code' => "+7",
                'capital' => "Moscow",
                'currency' => "RUB",
                'currency_symbol' => "₽",
                'active' => '1'
            ],
            [
                'name' => "Rwanda",
                'short_name' => "Rwanda",
                'iso2' => "RW",
                'iso3' => "RWA",
                'numeric_code' => "646",
                'calling_code' => "+250",
                'capital' => "Kigali",
                'currency' => "RWF",
                'currency_symbol' => "FRw"
            ],
            [
                'name' => "Saint Helena",
                'short_name' => "Saint Helena",
                'iso2' => "SH",
                'iso3' => "SHN",
                'numeric_code' => "654",
                'calling_code' => "+290",
                'capital' => "Jamestown",
                'currency' => "SHP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "Saint Kitts and Nevis",
                'short_name' => "Saint Kitts and Nevis",
                'iso2' => "KN",
                'iso3' => "KNA",
                'numeric_code' => "659",
                'calling_code' => "+1",
                'capital' => "Basseterre",
                'currency' => "XCD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Saint Lucia",
                'short_name' => "Saint Lucia",
                'iso2' => "LC",
                'iso3' => "LCA",
                'numeric_code' => "662",
                'calling_code' => "+1",
                'capital' => "Castries",
                'currency' => "XCD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Saint Pierre and Miquelon",
                'short_name' => "Saint Pierre and Miquelon",
                'iso2' => "PM",
                'iso3' => "SPM",
                'numeric_code' => "666",
                'calling_code' => "+508",
                'capital' => "Saint-Pierre",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Saint Vincent and the Grenadines",
                'short_name' => "Saint Vincent and the Grenadines",
                'iso2' => "VC",
                'iso3' => "VCT",
                'numeric_code' => "670",
                'calling_code' => "+1",
                'capital' => "Kingstown",
                'currency' => "XCD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Saint-Barthelemy",
                'short_name' => "Saint-Barthelemy",
                'iso2' => "BL",
                'iso3' => "BLM",
                'numeric_code' => "652",
                'calling_code' => "+590",
                'capital' => "Gustavia",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Saint-Martin (French part)",
                'short_name' => "Saint-Martin (French part)",
                'iso2' => "MF",
                'iso3' => "MAF",
                'numeric_code' => "663",
                'calling_code' => "+590",
                'capital' => "Marigot",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Samoa",
                'short_name' => "Samoa",
                'iso2' => "WS",
                'iso3' => "WSM",
                'numeric_code' => "882",
                'calling_code' => "+685",
                'capital' => "Apia",
                'currency' => "WST",
                'currency_symbol' => "SAT"
            ],
            [
                'name' => "San Marino",
                'short_name' => "San Marino",
                'iso2' => "SM",
                'iso3' => "SMR",
                'numeric_code' => "674",
                'calling_code' => "+378",
                'capital' => "San Marino",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Sao Tome and Principe",
                'short_name' => "Sao Tome and Principe",
                'iso2' => "ST",
                'iso3' => "STP",
                'numeric_code' => "678",
                'calling_code' => "+239",
                'capital' => "Sao Tome",
                'currency' => "STD",
                'currency_symbol' => "Db"
            ],
            [
                'name' => "Saudi Arabia",
                'short_name' => "Saudi Arabia",
                'iso2' => "SA",
                'iso3' => "SAU",
                'numeric_code' => "682",
                'calling_code' => "+966",
                'capital' => "Riyadh",
                'currency' => "SAR",
                'currency_symbol' => "﷼"
            ],
            [
                'name' => "Senegal",
                'short_name' => "Senegal",
                'iso2' => "SN",
                'iso3' => "SEN",
                'numeric_code' => "686",
                'calling_code' => "+221",
                'capital' => "Dakar",
                'currency' => "XOF",
                'currency_symbol' => "CFA"
            ],
            [
                'name' => "Serbia",
                'short_name' => "Serbia",
                'iso2' => "RS",
                'iso3' => "SRB",
                'numeric_code' => "688",
                'calling_code' => "+381",
                'capital' => "Belgrade",
                'currency' => "RSD",
                'currency_symbol' => "din"
            ],
            [
                'name' => "Seychelles",
                'short_name' => "Seychelles",
                'iso2' => "SC",
                'iso3' => "SYC",
                'numeric_code' => "690",
                'calling_code' => "+248",
                'capital' => "Victoria",
                'currency' => "SCR",
                'currency_symbol' => "SRe"
            ],
            [
                'name' => "Sierra Leone",
                'short_name' => "Sierra Leone",
                'iso2' => "SL",
                'iso3' => "SLE",
                'numeric_code' => "694",
                'calling_code' => "+232",
                'capital' => "Freetown",
                'currency' => "SLL",
                'currency_symbol' => "Le"
            ],
            [
                'name' => "Singapore",
                'short_name' => "Singapore",
                'iso2' => "SG",
                'iso3' => "SGP",
                'numeric_code' => "702",
                'calling_code' => "+65",
                'capital' => "Singapur",
                'currency' => "SGD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Sint Maarten (Dutch part)",
                'short_name' => "Sint Maarten (Dutch part)",
                'iso2' => "SX",
                'iso3' => "SXM",
                'numeric_code' => "534",
                'calling_code' => "+1721",
                'capital' => "Philipsburg",
                'currency' => "ANG",
                'currency_symbol' => "ƒ"
            ],
            [
                'name' => "Slovakia",
                'short_name' => "Slovakia",
                'iso2' => "SK",
                'iso3' => "SVK",
                'numeric_code' => "703",
                'calling_code' => "+421",
                'capital' => "Bratislava",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Slovenia",
                'short_name' => "Slovenia",
                'iso2' => "SI",
                'iso3' => "SVN",
                'numeric_code' => "705",
                'calling_code' => "+386",
                'capital' => "Ljubljana",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Solomon Islands",
                'short_name' => "Solomon Islands",
                'iso2' => "SB",
                'iso3' => "SLB",
                'numeric_code' => "90",
                'calling_code' => "+677",
                'capital' => "Honiara",
                'currency' => "SBD",
                'currency_symbol' => "Si$"
            ],
            [
                'name' => "Somalia",
                'short_name' => "Somalia",
                'iso2' => "SO",
                'iso3' => "SOM",
                'numeric_code' => "706",
                'calling_code' => "+252",
                'capital' => "Mogadishu",
                'currency' => "SOS",
                'currency_symbol' => "Sh.so."
            ],
            [
                'name' => "South Africa",
                'short_name' => "South Africa",
                'iso2' => "ZA",
                'iso3' => "ZAF",
                'numeric_code' => "710",
                'calling_code' => "+27",
                'capital' => "Pretoria",
                'currency' => "ZAR",
                'currency_symbol' => "R",
                'active' => '1'
            ],
            [
                'name' => "South Georgia",
                'short_name' => "South Georgia",
                'iso2' => "GS",
                'iso3' => "SGS",
                'numeric_code' => "239",
                'calling_code' => "+500",
                'capital' => "Grytviken",
                'currency' => "GBP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "South Korea",
                'short_name' => "South Korea",
                'iso2' => "KR",
                'iso3' => "KOR",
                'numeric_code' => "410",
                'calling_code' => "+82",
                'capital' => "Seoul",
                'currency' => "KRW",
                'currency_symbol' => "₩"
            ],
            [
                'name' => "South Sudan",
                'short_name' => "South Sudan",
                'iso2' => "SS",
                'iso3' => "SSD",
                'numeric_code' => "728",
                'calling_code' => "+211",
                'capital' => "Juba",
                'currency' => "SSP",
                'currency_symbol' => "£"
            ],
            [
                'name' => "Spain",
                'short_name' => "Spain",
                'iso2' => "ES",
                'iso3' => "ESP",
                'numeric_code' => "724",
                'calling_code' => "+34",
                'capital' => "Madrid",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Sri Lanka",
                'short_name' => "Sri Lanka",
                'iso2' => "LK",
                'iso3' => "LKA",
                'numeric_code' => "144",
                'calling_code' => "+94",
                'capital' => "Colombo",
                'currency' => "LKR",
                'currency_symbol' => "Rs"
            ],
            [
                'name' => "Sudan",
                'short_name' => "Sudan",
                'iso2' => "SD",
                'iso3' => "SDN",
                'numeric_code' => "729",
                'calling_code' => "+249",
                'capital' => "Khartoum",
                'currency' => "SDG",
                'currency_symbol' => ".س.ج"
            ],
            [
                'name' => "Suriname",
                'short_name' => "Suriname",
                'iso2' => "SR",
                'iso3' => "SUR",
                'numeric_code' => "740",
                'calling_code' => "+597",
                'capital' => "Paramaribo",
                'currency' => "SRD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Svalbard and Jan Mayen Islands",
                'short_name' => "Svalbard and Jan Mayen Islands",
                'iso2' => "SJ",
                'iso3' => "SJM",
                'numeric_code' => "744",
                'calling_code' => "+47",
                'capital' => "Longyearbyen",
                'currency' => "NOK",
                'currency_symbol' => "ko"
            ],
            [
                'name' => "Sweden",
                'short_name' => "Sweden",
                'iso2' => "SE",
                'iso3' => "SWE",
                'numeric_code' => "752",
                'calling_code' => "+46",
                'capital' => "Stockholm",
                'currency' => "SEK",
                'currency_symbol' => "ko"
            ],
            [
                'name' => "Switzerland",
                'short_name' => "Switzerland",
                'iso2' => "CH",
                'iso3' => "CHE",
                'numeric_code' => "756",
                'calling_code' => "+41",
                'capital' => "Bern",
                'currency' => "CHF",
                'currency_symbol' => "CHf"
            ],
            [
                'name' => "Syria",
                'short_name' => "Syria",
                'iso2' => "SY",
                'iso3' => "SYR",
                'numeric_code' => "760",
                'calling_code' => "+963",
                'capital' => "Damascus",
                'currency' => "SYP",
                'currency_symbol' => "LS"
            ],
            [
                'name' => "Taiwan",
                'short_name' => "Taiwan",
                'iso2' => "TW",
                'iso3' => "TWN",
                'numeric_code' => "158",
                'calling_code' => "+886",
                'capital' => "Taipei",
                'currency' => "TWD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Tajikistan",
                'short_name' => "Tajikistan",
                'iso2' => "TJ",
                'iso3' => "TJK",
                'numeric_code' => "762",
                'calling_code' => "+992",
                'capital' => "Dushanbe",
                'currency' => "TJS",
                'currency_symbol' => "SM"
            ],
            [
                'name' => "Tanzania",
                'short_name' => "Tanzania",
                'iso2' => "TZ",
                'iso3' => "TZA",
                'numeric_code' => "834",
                'calling_code' => "+255",
                'capital' => "Dodoma",
                'currency' => "TZS",
                'currency_symbol' => "TSh"
            ],
            [
                'name' => "Thailand",
                'short_name' => "Thailand",
                'iso2' => "TH",
                'iso3' => "THA",
                'numeric_code' => "764",
                'calling_code' => "+66",
                'capital' => "Bangkok",
                'currency' => "THB",
                'currency_symbol' => "฿"
            ],
            [
                'name' => "The Bahamas",
                'short_name' => "The Bahamas",
                'iso2' => "BS",
                'iso3' => "BHS",
                'numeric_code' => "44",
                'calling_code' => "+1",
                'capital' => "Nassau",
                'currency' => "BSD",
                'currency_symbol' => "B$"
            ],
            [
                'name' => "The Gambia ",
                'short_name' => "The Gambia ",
                'iso2' => "GM",
                'iso3' => "GMB",
                'numeric_code' => "270",
                'calling_code' => "+220",
                'capital' => "Banjul",
                'currency' => "GMD",
                'currency_symbol' => "D"
            ],
            [
                'name' => "Timor-Leste",
                'short_name' => "Timor-Leste",
                'iso2' => "TL",
                'iso3' => "TLS",
                'numeric_code' => "626",
                'calling_code' => "+670",
                'capital' => "Dili",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Togo",
                'short_name' => "Togo",
                'iso2' => "TG",
                'iso3' => "TGO",
                'numeric_code' => "768",
                'calling_code' => "+228",
                'capital' => "Lome",
                'currency' => "XOF",
                'currency_symbol' => "CFA"
            ],
            [
                'name' => "Tokelau",
                'short_name' => "Tokelau",
                'iso2' => "TK",
                'iso3' => "TKL",
                'numeric_code' => "772",
                'calling_code' => "+690",
                'capital' => "nan",
                'currency' => "NZD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Tonga",
                'short_name' => "Tonga",
                'iso2' => "TO",
                'iso3' => "TON",
                'numeric_code' => "776",
                'calling_code' => "+676",
                'capital' => "Nuku'alofa",
                'currency' => "TOP",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Trinidad and Tobago",
                'short_name' => "Trinidad and Tobago",
                'iso2' => "TT",
                'iso3' => "TTO",
                'numeric_code' => "780",
                'calling_code' => "+1",
                'capital' => "Port of Spain",
                'currency' => "TTD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Tunisia",
                'short_name' => "Tunisia",
                'iso2' => "TN",
                'iso3' => "TUN",
                'numeric_code' => "788",
                'calling_code' => "+216",
                'capital' => "Tunis",
                'currency' => "TND",
                'currency_symbol' => "ت.د"
            ],
            [
                'name' => "Turkey",
                'short_name' => "Turkey",
                'iso2' => "TR",
                'iso3' => "TUR",
                'numeric_code' => "792",
                'calling_code' => "+90",
                'capital' => "Ankara",
                'currency' => "TRY",
                'currency_symbol' => "₺"
            ],
            [
                'name' => "Turkmenistan",
                'short_name' => "Turkmenistan",
                'iso2' => "TM",
                'iso3' => "TKM",
                'numeric_code' => "795",
                'calling_code' => "+993",
                'capital' => "Ashgabat",
                'currency' => "TMT",
                'currency_symbol' => "T"
            ],
            [
                'name' => "Turks and Caicos Islands",
                'short_name' => "Turks and Caicos Islands",
                'iso2' => "TC",
                'iso3' => "TCA",
                'numeric_code' => "796",
                'calling_code' => "+1",
                'capital' => "Cockburn Town",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Tuvalu",
                'short_name' => "Tuvalu",
                'iso2' => "TV",
                'iso3' => "TUV",
                'numeric_code' => "798",
                'calling_code' => "+688",
                'capital' => "Funafuti",
                'currency' => "AUD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Uganda",
                'short_name' => "Uganda",
                'iso2' => "UG",
                'iso3' => "UGA",
                'numeric_code' => "800",
                'calling_code' => "+256",
                'capital' => "Kampala",
                'currency' => "UGX",
                'currency_symbol' => "USh"
            ],
            [
                'name' => "Ukraine",
                'short_name' => "Ukraine",
                'iso2' => "UA",
                'iso3' => "UKR",
                'numeric_code' => "804",
                'calling_code' => "+380",
                'capital' => "Kyiv",
                'currency' => "UAH",
                'currency_symbol' => "₴"
            ],
            [
                'name' => "United Arab Emirates",
                'short_name' => "United Arab Emirates",
                'iso2' => "AE",
                'iso3' => "ARE",
                'numeric_code' => "784",
                'calling_code' => "+971",
                'capital' => "Abu Dhabi",
                'currency' => "AED",
                'currency_symbol' => "إ.د"
            ],
            [
                'name' => "United Kingdom",
                'short_name' => "United Kingdom",
                'iso2' => "GB",
                'iso3' => "GBR",
                'numeric_code' => "826",
                'calling_code' => "+44",
                'capital' => "London",
                'currency' => "GBP",
                'currency_symbol' => "£",
                'active' => '1'
            ],
            [
                'name' => "United States",
                'short_name' => "United States",
                'iso2' => "US",
                'iso3' => "USA",
                'numeric_code' => "840",
                'calling_code' => "+1",
                'capital' => "Washington",
                'currency' => "USD",
                'currency_symbol' => "$",
                'active' => '1'
            ],
            [
                'name' => "United States Minor Outlying Islands",
                'short_name' => "United States Minor Outlying Islands",
                'iso2' => "UM",
                'iso3' => "UMI",
                'numeric_code' => "581",
                'calling_code' => "+1",
                'capital' => "nan",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Uruguay",
                'short_name' => "Uruguay",
                'iso2' => "UY",
                'iso3' => "URY",
                'numeric_code' => "858",
                'calling_code' => "+598",
                'capital' => "Montevideo",
                'currency' => "UYU",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Uzbekistan",
                'short_name' => "Uzbekistan",
                'iso2' => "UZ",
                'iso3' => "UZB",
                'numeric_code' => "860",
                'calling_code' => "+998",
                'capital' => "Tashkent",
                'currency' => "UZS",
                'currency_symbol' => "лв"
            ],
            [
                'name' => "Vanuatu",
                'short_name' => "Vanuatu",
                'iso2' => "VU",
                'iso3' => "VUT",
                'numeric_code' => "548",
                'calling_code' => "+678",
                'capital' => "Port Vila",
                'currency' => "VUV",
                'currency_symbol' => "VT"
            ],
            [
                'name' => "Vatican City State (Holy See)",
                'short_name' => "Vatican City State (Holy See)",
                'iso2' => "VA",
                'iso3' => "VAT",
                'numeric_code' => "336",
                'calling_code' => "+379",
                'capital' => "Vatican City",
                'currency' => "EUR",
                'currency_symbol' => "€"
            ],
            [
                'name' => "Venezuela",
                'short_name' => "Venezuela",
                'iso2' => "VE",
                'iso3' => "VEN",
                'numeric_code' => "862",
                'calling_code' => "+58",
                'capital' => "Caracas",
                'currency' => "VES",
                'currency_symbol' => "Bs"
            ],
            [
                'name' => "Vietnam",
                'short_name' => "Vietnam",
                'iso2' => "VN",
                'iso3' => "VNM",
                'numeric_code' => "704",
                'calling_code' => "+84",
                'capital' => "Hanoi",
                'currency' => "VND",
                'currency_symbol' => "₫"
            ],
            [
                'name' => "Virgin Islands (British)",
                'short_name' => "Virgin Islands (British)",
                'iso2' => "VG",
                'iso3' => "VGB",
                'numeric_code' => "92",
                'calling_code' => "+1",
                'capital' => "Road Town",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Virgin Islands (US)",
                'short_name' => "Virgin Islands (US)",
                'iso2' => "VI",
                'iso3' => "VIR",
                'numeric_code' => "850",
                'calling_code' => "+1",
                'capital' => "Charlotte Amalie",
                'currency' => "USD",
                'currency_symbol' => "$"
            ],
            [
                'name' => "Wallis and Futuna Islands",
                'short_name' => "Wallis and Futuna Islands",
                'iso2' => "WF",
                'iso3' => "WLF",
                'numeric_code' => "876",
                'calling_code' => "+681",
                'capital' => "Mata Utu",
                'currency' => "XPF",
                'currency_symbol' => "₣"
            ],
            [
                'name' => "Western Sahara",
                'short_name' => "Western Sahara",
                'iso2' => "EH",
                'iso3' => "ESH",
                'numeric_code' => "732",
                'calling_code' => "+212",
                'capital' => "El-Aaiun",
                'currency' => "MAD",
                'currency_symbol' => "MAD"
            ],
            [
                'name' => "Yemen",
                'short_name' => "Yemen",
                'iso2' => "YE",
                'iso3' => "YEM",
                'numeric_code' => "887",
                'calling_code' => "+967",
                'capital' => "Sanaa",
                'currency' => "YER",
                'currency_symbol' => "﷼"
            ],
            [
                'name' => "Zambia",
                'short_name' => "Zambia",
                'iso2' => "ZM",
                'iso3' => "ZMB",
                'numeric_code' => "894",
                'calling_code' => "+260",
                'capital' => "Lusaka",
                'currency' => "ZMW",
                'currency_symbol' => "ZK"
            ],
            [
                'name' => "Zimbabwe",
                'short_name' => "Zimbabwe",
                'iso2' => "ZW",
                'iso3' => "ZWE",
                'numeric_code' => "716",
                'calling_code' => "+263",
                'capital' => "Harare",
                'currency' => "ZWL",
                'currency_symbol' => "$"
            ]
       ];

       foreach ($countries as $country) {
           SystemCountry::create($country);
       }
//        $this->command->info(class_basename(static::class) . ' seeded successfully!');
   }
}
