<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run()
    {

    User::create([
            'email' => 'thisisg@gmail.com',
            'name' => 'Gareth Redfern-Shaw',
            'first_name' => 'Gareth',
            'middle_name' => 'Sebastian',
            'last_name' => 'Redfern-Shaw',
            'preferred_name' => 'Gareth',
            'password' => 'rcp@UHE-nmq_kmw0qzk',
            'picture' => 'https://s3.us-east-2.amazonaws.com/storage.r2.rosterfy.com/misc/0miv/0mivWeAQHRyRF3A0pxhLmaFYX3fHjqW1o40elK19.jpg',
            'is_sys_admin' => '1',
            'is_team_leader' => '0',
            'email_verified_at' => now(),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        User::create([
            'email' => 'hyacinth_chu@yahoo.com',
            'name' => 'Hyacinth Chu',
            'first_name' => 'Hyacinth',
            'middle_name' => '',
            'last_name' => 'Chu',
            'preferred_name' => 'Hyacinth',
            'password' => 'default_pa55word!',
            'picture' => 'https://jp.citigatedewerogerson.com/jp/wp-content/uploads/sites/10/2017/11/Hyacinth-Chu-300x288-1.jpg',
            'is_admin' => 1,
            'is_athlete' => 0,
            'is_guide' => 1,
            'is_team_leader' => 1,
            'email_verified_at' => '2022-10-31 04:58:39',
            'created_at' => '2022-10-31 04:58:39',
            'updated_at' => '2024-03-16 06:11:51',
        ]);
        User::create([
            'email' => 'hframirezjr@yahoo.com',
            'name' => 'Hector Ramirez',
            'first_name' => 'Hector',
            'middle_name' => '',
            'last_name' => 'Ramirez',
            'preferred_name' => 'Hector',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_admin' => 1,
            'is_athlete' => 0,
            'is_guide' => 1,
            'is_team_leader' => 1,
            'email_verified_at' => '2022-10-31 04:58:39',
            'created_at' => '2022-10-31 04:58:39',
            'updated_at' => '2024-03-16 06:11:51',
        ]);
        User::create([
            'email' => 'Tiannambiscone@gmail.com',
            'name' => 'Tianna Biscone',
            'first_name' => 'Tianna',
            'middle_name' => '',
            'last_name' => 'Biscone',
            'preferred_name' => 'Tianna',
            'password' => 'default_pa55word!',
            'picture' => 'https://s3.us-east-2.amazonaws.com/storage.r2.rosterfy.com/misc/NUKD/NUKDhAgu5Q9qQwHaQk0bwI61jpRyFcHXUVdBd8KO.jpg',
            'is_admin' => 1,
            'is_athlete' => 0,
            'is_guide' => 1,
            'is_team_leader' => 1,
            'email_verified_at' => '2022-10-06 19:41:24',
            'created_at' => '2022-10-06 19:41:24',
            'updated_at' => '2024-07-22 18:24:33',
        ]);
        User::create([
            'email' => 'cfee@achillesinternational.org',
            'name' => 'Chandler Fee',
            'first_name' => 'Chandler',
            'middle_name' => null,
            'last_name' => 'Fee',
            'preferred_name' => 'Chandler',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_sys_admin' => '1',
            'is_team_leader' => '1',
            'email_verified_at' => now(),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        User::create([
            'email' => 'cbass@achillesinternational.org',
            'name' => 'Casey Bass',
            'first_name' => 'Casey',
            'middle_name' => '',
            'last_name' => 'Bass',
            'preferred_name' => 'Casey',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_admin' => 1,
            'is_athlete' => 0,
            'is_guide' => 1,
            'is_team_leader' => 1,
            'email_verified_at' => '2022-11-02 19:41:21',
            'created_at' => '2022-11-02 19:41:21',
            'updated_at' => '2024-07-24 08:20:32',
        ]);
        User::create([
            'email' => 'mcueto@achillesinternational.org',
            'name' => 'Michaela Cueto',
            'first_name' => 'Michaela',
            'middle_name' => '',
            'last_name' => 'Cueto',
            'preferred_name' => 'Michaela',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_admin' => 1,
            'is_athlete' => 0,
            'is_guide' => 1,
            'is_team_leader' => 1,
            'email_verified_at' => '2022-11-11 19:06:35',
            'created_at' => '2022-11-11 19:06:35',
            'updated_at' => '2024-06-10 20:20:18',
        ]);
        User::create([
            'email' => 'molly.robustelli@gmail.com',
            'name' => 'Molly Robustelli',
            'first_name' => 'Molly',
            'middle_name' => '',
            'last_name' => 'Robustelli',
            'preferred_name' => 'Molly',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_admin' => 1,
            'is_athlete' => 0,
            'is_guide' => 1,
            'is_team_leader' => 1,
            'email_verified_at' => '2022-10-25 06:12:10',
            'created_at' => '2022-10-25 06:12:10',
            'updated_at' => '2023-08-26 14:24:54',
        ]);
        User::create([
            'email' => 'jday0210@gmail.com',
            'name' => 'Julia Day',
            'first_name' => 'Julia',
            'middle_name' => null,
            'last_name' => 'Day',
            'preferred_name' => 'Julia',
            'password' => 'EpicTriLady!',
            'picture' => 'https://fordhamsports.com/images/2016/10/17/DayHS2016.jpg',
            'is_sys_admin' => '1',
            'is_team_leader' => '1',
            'email_verified_at' => now(),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        User::create([
            'email' => 'kchu@achillesinternational.org',
            'name' => 'Kathryn Chu',
            'first_name' => 'Kathryn',
            'middle_name' => '',
            'last_name' => 'Chu',
            'preferred_name' => 'Kathryn',
            'password' => 'default_pa55word!',
            'picture' => 'https://s3.us-east-2.amazonaws.com/storage.r2.rosterfy.com/misc/3wQL/3wQLHrTFltxmdNidHpwsFIL0usFwPhnTt6xTQy18.jpg',
            'is_admin' => '1',
            'is_team_leader' => '0',
            'email_verified_at' => '2022-05-12 23:55:56',
            'created_at' => '2022-05-12 23:55:56',
            'updated_at' => '2024-07-03 17:38:57',
        ]);
        User::create([
            'email' => 'rherman@achillesinternational.org',
            'name' => 'Richard Herman',
            'first_name' => 'Richard',
            'middle_name' => '',
            'last_name' => 'Herman',
            'preferred_name' => 'Rich',
            'password' => 'default_pa55word!',
            'picture' => 'https://s3.us-east-2.amazonaws.com/storage.r2.rosterfy.com/misc/7Bqk/7Bqk6fVO3I3T8FRN78rrONjl5PJlJrA02aRiWVu5.jpg',
            'is_sys_admin' => '1',
            'is_team_leader' => '0',
            'email_verified_at' => '2022-05-12 23:56:34',
            'created_at' => '2022-05-12 23:56:34',
            'updated_at' => '2024-07-16 10:31:35',
        ]);
        User::create([
            'email' => 'connecticut@achillesinternational.org',
            'name' => 'Connecticut Chapter',
            'first_name' => 'Connecticut',
            'middle_name' => '',
            'last_name' => 'Chapter',
            'preferred_name' => '',
            'password' => 'default_pa55word!',
            'picture' => 'https://s3.us-east-2.amazonaws.com/storage.r2.rosterfy.com/misc/snUD/snUDtlb1pSoq1reTqQ9azpxTNN4Gzrh3lZbDM2pb.jpg',
            'is_admin' => '1',
            'is_team_leader' => '0',
            'email_verified_at' => '2022-08-16 23:56:47',
            'created_at' => '2022-08-16 23:56:47',
            'updated_at' => '2023-09-14 18:10:10',
        ]);
        User::create([
            'email' => 'sgibbs8885@gmail.com',
            'name' => 'Sean Gibbs',
            'first_name' => 'Sean',
            'middle_name' => '',
            'last_name' => 'Gibbs',
            'preferred_name' => 'Sean Gibbs',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_team_leader' => '0',
            'email_verified_at' => '2022-10-07 01:34:24',
            'created_at' => '2022-10-07 01:34:24',
            'updated_at' => '2023-09-05 23:04:26',
        ]);
        User::create([
            'email' => 'zqstew@gmail.com',
            'name' => 'Zachary Stewart',
            'first_name' => 'Zachary',
            'middle_name' => '',
            'last_name' => 'Stewart',
            'preferred_name' => 'Quinn',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_team_leader' => '0',
            'email_verified_at' => '2022-10-07 01:38:29',
            'created_at' => '2022-10-07 01:38:29',
            'updated_at' => '2023-08-26 15:53:08',
        ]);
        User::create([
            'email' => 'Kscudiere@outlook.com',
            'name' => 'Kyle Scudiere',
            'first_name' => 'Kyle',
            'middle_name' => '',
            'last_name' => 'Scudiere',
            'preferred_name' => 'Kyle',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_team_leader' => '0',
            'email_verified_at' => '2022-10-07 01:38:44',
            'created_at' => '2022-10-07 01:38:44',
            'updated_at' => '2024-06-22 06:16:15',
        ]);
        User::create([
            'email' => 'tinazxcaruso@gmail.com',
            'name' => 'Tina Zhu Xi Caruso',
            'first_name' => 'Tina Zhu Xi',
            'middle_name' => '',
            'last_name' => 'Caruso',
            'preferred_name' => 'Tina Zhu Xi',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_team_leader' => '0',
            'email_verified_at' => '2022-10-07 01:39:02',
            'created_at' => '2022-10-07 01:39:02',
            'updated_at' => '2024-07-10 03:10:19',
        ]);
        User::create([
            'email' => 'erin.sabato@gmail.com',
            'name' => 'Erin Sabato',
            'first_name' => 'Erin',
            'middle_name' => '',
            'last_name' => 'Sabato',
            'preferred_name' => 'Erin',
            'password' => 'default_pa55word!',
            'picture' => '',
            'is_team_leader' => '0',
            'email_verified_at' => '2022-10-07 01:40:54',
            'created_at' => '2022-10-07 01:40:54',
            'updated_at' => '2023-08-26 10:53:03',
        ]);

//        $this->command->info(class_basename(static::class) . ' seeded successfully!');
    }
}
